namespace Prism {
public static class Levels {
 public static Level[] Create()=>new[]{
  new Level {Id="reflection-01",Name="İlk yansıma",Lesson="Işığa yeni bir yön ver.",Hint="Aynayı ışığın üzerine koy. 45° ile yukarı yansıt.",Source=new V(-4,-2),Direction=new V(1,0),Stock=new[]{Kind.Mirror},Goals=new[]{new Goal(new V(0,3),-1)},Solution=new[]{new Piece(Kind.Mirror,new V(0,-2),45)}},
  new Level {Id="dispersion-01",Name="Beyazın içindeki",Lesson="Prizma ile renkleri ortaya çıkar.",Hint="Prizmayı ışığın üzerine taşı ve renk yelpazesini hedefe çevir.",Source=new V(-4,0),Direction=new V(1,0),Stock=new[]{Kind.Prism},Goals=new[]{new Goal(new V(3,-2),3)},Solution=new[]{new Piece(Kind.Prism,new V(0,0),90)}},
  new Level {Id="selective-green-01",Name="Bir ışık, iki yol",Lesson="Yeşili ayır, kırmızıyı geçir.",Hint="Yeşil seçici ayna yeşili yansıtır, diğer renkleri geçirir.",Source=new V(-4,0),Direction=new V(1,0),Stock=new[]{Kind.Green},Goals=new[]{new Goal(new V(-1,3),3),new Goal(new V(3,0),6)},Solution=new[]{new Piece(Kind.Green,new V(-1,0),45)}},
  new Level {Id="focus-01",Name="Odak noktası",Lesson="Geniş ışığı küçük bir hedefte topla.",Hint="Lensi dik tut. Odak noktası lensten 2,4 birim uzakta.",Source=new V(-4,0),Direction=new V(1,0),Width=1.2,Stock=new[]{Kind.Lens},Goals=new[]{new Goal(new V(2.4,0),-1){Radius=0.17,Threshold=0.8}},Solution=new[]{new Piece(Kind.Lens,new V(0,0),90)}},
  new Level {Id="garden-01",Name="Işık bahçesi",Lesson="Üç parçayla iki hedefi birlikte aydınlat.",Hint="Önce aynayla yukarı dön. Yeşili sağa ayır, kalan ışığı lensle topla.",Source=new V(-4,-3),Direction=new V(1,0),Width=0.75,Stock=new[]{Kind.Mirror,Kind.Green,Kind.Lens},Goals=new[]{new Goal(new V(2.5,0),3),new Goal(new V(-2,3.4),6){Radius=0.19,Threshold=0.75}},Walls=new[]{new Wall(new V(-0.5,-4),new V(-0.5,-1))},Solution=new[]{new Piece(Kind.Mirror,new V(-2,-3),45),new Piece(Kind.Green,new V(-2,0),45),new Piece(Kind.Lens,new V(-2,1),0)}},
  new Level {Id="selective-red-01",Name="Kızıl yankı",Lesson="Kırmızı ışığı ayır, kalanı tayfa böl.",Hint="Kırmızı seçiciyle kırmızıyı yukarı gönder. Prizmayla yeşili hedefe kır.",Source=new V(-4,0),Direction=new V(1,0),Width=0.35,Stock=new[]{Kind.Red,Kind.Prism},Goals=new[]{new Goal(new V(-1,3),6){Radius=0.45,Threshold=0.4},new Goal(new V(4,-2),3){Radius=0.45,Threshold=0.2}},Solution=new[]{new Piece(Kind.Red,new V(-1,0),45),new Piece(Kind.Prism,new V(1,0),90)}},
  new Level {Id="water-01",Name="Suyun hafızası",Lesson="Işık suya girdiğinde yön değiştirir.",Hint="Aynayla ışığı suya yönlendir. Küre ile hedefe odakla.",Source=new V(-4,2),Direction=new V(1,0),Width=0.4,Stock=new[]{Kind.Mirror,Kind.Sphere},WaterZones=new[]{new WaterZone(new V(-1.5,-3),new V(3,0.5),1.333)},Walls=new[]{new Wall(new V(0,0.5),new V(0,3.5))},Goals=new[]{new Goal(new V(1.5,-2.3),-1){Radius=0.35,Threshold=0.4}},Solution=new[]{new Piece(Kind.Mirror,new V(-2,2),337.5),new Piece(Kind.Sphere,new V(1.0,-1.5),0)}},
  new Level {Id="symphony-01",Name="Optik senfoni",Lesson="Dört parça, üç hedef, tek bir uyum.",Hint="Aynayla yukarı dön. Kırmızı seçiciyle kırmızıyı suya ayır. Prizmayla yeşil ve maviyi ayır, küreyle odakla.",Source=new V(-4,-2.5),Direction=new V(1,0),Width=0.4,Stock=new[]{Kind.Mirror,Kind.Red,Kind.Prism,Kind.Sphere},Walls=new[]{new Wall(new V(-0.5,-4),new V(-0.5,-0.8)),new Wall(new V(0.5,0.5),new V(0.5,3.5))},WaterZones=new[]{new WaterZone(new V(0.0,-1.5),new V(3.5,0.5),1.333)},Goals=new[]{new Goal(new V(2.3,-0.5),6){Radius=0.35,Threshold=0.35},new Goal(new V(-3.0,2.3),3){Radius=0.45,Threshold=0.2},new Goal(new V(-0.3,2.8),1){Radius=0.45,Threshold=0.2}},Solution=new[]{new Piece(Kind.Mirror,new V(-2,-2.5),45),new Piece(Kind.Red,new V(-2,-0.5),45),new Piece(Kind.Sphere,new V(1.3,-0.5),0),new Piece(Kind.Prism,new V(-2,1.2),90)}}
  };
}
}
